# You can use this file to create a conda environment for this pipeline:
#   conda env create -f environment.yml
name: nf-core-nanornabam-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # TODO nf-core: Add required software dependencies here
  - fastqc=0.11.8
  - multiqc=1.7
  - r-base=3.6.1
  - bioconductor-deseq2=1.26.0
  - bioconductor-drimseq=1.14.0
  - bioconductor-dexseq=1.32.0
